# -----------------------------------------------------------------------------
# EnclaveInstance Composition (Helm provider) - BYOC version
# Maps EnclaveInstance spec to Helm ProviderConfig + Helm Release
# This version is for "Bring Your Own Cluster" scenarios
# -----------------------------------------------------------------------------
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: enclave-helm-byoc
  labels:
    crossplane.io/xrd: enclaveinstances.usenabla.com
    provider: helm
    enclave-type: byoc
spec:
  compositeTypeRef:
    apiVersion: usenabla.com/v1alpha1
    kind: EnclaveInstance

  patchSets:
    - name: common-labels
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.customer
          toFieldPath: metadata.labels["usenabla.com/customer"]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.environment
          toFieldPath: metadata.labels["usenabla.com/environment"]

  resources:
    # -------------------------------------------------------------------------
    # ProviderConfig: per-enclave provider-helm config that reads kubeconfig from Secret
    # -------------------------------------------------------------------------
    - name: providerconfig
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        metadata:
          # metadata.name patched from composite customer (below)
          namespace: crossplane-system
        spec:
          # credentials are loaded from a Secret containing kubeconfig (key: kubeconfig)
          credentials:
            source: Secret
            secretRef:
              namespace: crossplane-system
              # name patched from composite's existingCluster.kubeconfigSecretRef
              name: "" 
              key: kubeconfig
          # optional default namespace for Releases created with this provider
          defaultNamespace: default
      patches:
        # name this provider-config: provider-helm-enclave-<customer>
        - type: FromCompositeFieldPath
          fromFieldPath: spec.customer
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "provider-helm-enclave-%s"

        # secret name for kubeconfig from the BYOC field
        - type: FromCompositeFieldPath
          fromFieldPath: spec.existingCluster.kubeconfigSecretRef
          toFieldPath: spec.credentials.secretRef.name

    # -------------------------------------------------------------------------
    # Helm Release - deploys the enclave chart using the ProviderConfig above
    # -------------------------------------------------------------------------
    - name: enclave-release
      base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: ""   # patched below from customer
          namespace: crossplane-system
        spec:
          forProvider:
            chart:
              # replace with your real chart name & repo
              name: nabla-enclave
              repository: "https://charts.usenabla.com"
              version: "0.1.0"
            releaseName: ""   # patched below
            namespace: ""     # patched below (target namespace in cluster)
            # values is a map; patches will populate values.* entries
            values: {}
          providerConfigRef:
            name: ""  # patched below to match providerconfig above
      patches:
        # release & metadata names from customer
        - type: FromCompositeFieldPath
          fromFieldPath: spec.customer
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "enclave-release-%s"

        - type: FromCompositeFieldPath
          fromFieldPath: spec.customer
          toFieldPath: spec.forProvider.releaseName
          transforms:
            - type: string
              string:
                fmt: "enclave-%s"

        # target install namespace (chart namespace) - optional, uses clusterPrefix if provided
        - type: FromCompositeFieldPath
          fromFieldPath: spec.clusterPrefix
          toFieldPath: spec.forProvider.namespace
          transforms:
            - type: string
              string:
                fmt: "%s-ns"

        # wire providerConfigRef to the providerconfig created above
        - type: FromCompositeFieldPath
          fromFieldPath: spec.customer
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: string
              string:
                fmt: "provider-helm-enclave-%s"

        # --- Map EnclaveInstance fields to Helm chart values ---

        # environment -> values.environment
        - type: FromCompositeFieldPath
          fromFieldPath: spec.environment
          toFieldPath: spec.forProvider.values.environment
        # domain -> values.domain
        - type: FromCompositeFieldPath
          fromFieldPath: spec.domain
          toFieldPath: spec.forProvider.values.domain
        # clusterPrefix -> values.clusterPrefix
        - type: FromCompositeFieldPath
          fromFieldPath: spec.clusterPrefix
          toFieldPath: spec.forProvider.values.clusterPrefix
        # resource prefix (customer) -> values.resourcePrefix
        - type: FromCompositeFieldPath
          fromFieldPath: spec.customer
          toFieldPath: spec.forProvider.values.resourcePrefix
        # azure.region -> values.location (if chart expects region)
        - type: FromCompositeFieldPath
          fromFieldPath: spec.azure.region
          toFieldPath: spec.forProvider.values.location
        # teleport.acmeEmail -> values.teleport.acmeEmail
        - type: FromCompositeFieldPath
          fromFieldPath: spec.teleport.acmeEmail
          toFieldPath: spec.forProvider.values.teleport.acmeEmail
        # teleport config (example nested JSON structure) - if chart expects full object
        - type: FromCompositeFieldPath
          fromFieldPath: spec.teleport.acmeEmail
          toFieldPath: spec.forProvider.values.teleport.acmeEnabledEmail
          transforms:
            - type: string
              string:
                fmt: '{"acme_enabled": true, "acme_email":"%s", "second_factor":"webauthn"}'
        # CUI enabled flag -> values.features.cuiEnabled
        - type: FromCompositeFieldPath
          fromFieldPath: spec.features.cuiEnabled
          toFieldPath: spec.forProvider.values.features.cuiEnabled
          transforms:
            - type: convert
              convert:
                toType: bool

        # --- Status patches ---

        # map Release provider status to composite status.phase
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.state
          toFieldPath: status.phase
          transforms:
            - type: map
              map:
                deployed: Ready
                pending_install: Provisioning
                failed: Error

        # Compose a cluster FQDN from clusterPrefix + domain
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.clusterPrefix
              - fromFieldPath: spec.domain
            strategy: string
            string:
              fmt: "%s.%s"
          toFieldPath: status.clusterFqdn

        # expose where to find kubeconfig (secret name) in the composite status
        - type: FromCompositeFieldPath
          fromFieldPath: spec.existingCluster.kubeconfigSecretRef
          toFieldPath: status.kubeconfigSecretName

      connectionDetails:
        # Expose the kubeconfig secret name as a connection detail
        - name: kubeconfigSecretName
          fromFieldPath: status.kubeconfigSecretName
          fromConnectionSecretKey: kubeconfigSecretName
        # Expose the cluster FQDN as a connection detail
        - name: clusterFqdn
          fromFieldPath: status.clusterFqdn
          fromConnectionSecretKey: clusterFqdn