# -----------------------------------------------------------------------------
# EnclaveInstance Composition (Terraform provider)
# Maps EnclaveInstance spec to Terraform Workspace
# -----------------------------------------------------------------------------
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: enclave-terraform
  labels:
    crossplane.io/xrd: enclaveinstances.usenabla.com
    provider: terraform
spec:
  compositeTypeRef:
    apiVersion: usenabla.com/v1alpha1
    kind: EnclaveInstance

  patchSets:
    - name: common-labels
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.customer
          toFieldPath: metadata.labels["usenabla.com/customer"]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.environment
          toFieldPath: metadata.labels["usenabla.com/environment"]

  resources:
    # -------------------------------------------------------------------------
    # Terraform Workspace - provisions the enclave using Terraform
    # -------------------------------------------------------------------------
    - name: enclave-workspace
      base:
        apiVersion: tf.upbound.io/v1beta1
        kind: Workspace
        metadata:
          name: ""   # patched below from customer
          namespace: crossplane-system
        spec:
          forProvider:
            # variables is a map; patches will populate variables.* entries
            variables: {}
          providerConfigRef:
            name: terraform-cloud
      patches:
        # workspace name from customer
        - type: FromCompositeFieldPath
          fromFieldPath: spec.customer
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "enclave-workspace-%s"

        # --- Map EnclaveInstance fields to Terraform variables ---

        # customer -> variables.customer
        - type: FromCompositeFieldPath
          fromFieldPath: spec.customer
          toFieldPath: spec.forProvider.variables.customer
        # environment -> variables.environment
        - type: FromCompositeFieldPath
          fromFieldPath: spec.environment
          toFieldPath: spec.forProvider.variables.environment
        # domain -> variables.domain
        - type: FromCompositeFieldPath
          fromFieldPath: spec.domain
          toFieldPath: spec.forProvider.variables.domain
        # clusterPrefix -> variables.cluster_prefix
        - type: FromCompositeFieldPath
          fromFieldPath: spec.clusterPrefix
          toFieldPath: spec.forProvider.variables.cluster_prefix
        # azure.region -> variables.location
        - type: FromCompositeFieldPath
          fromFieldPath: spec.azure.region
          toFieldPath: spec.forProvider.variables.location
        # teleport.acmeEmail -> variables.teleport_acme_email
        - type: FromCompositeFieldPath
          fromFieldPath: spec.teleport.acmeEmail
          toFieldPath: spec.forProvider.variables.teleport_acme_email
        # features.cuiEnabled -> variables.cui_enabled
        - type: FromCompositeFieldPath
          fromFieldPath: spec.features.cuiEnabled
          toFieldPath: spec.forProvider.variables.cui_enabled
          transforms:
            - type: convert
              convert:
                toType: bool

        # --- Status patches ---

        # map Workspace ready condition to composite status.phase
        - type: ToCompositeFieldPath
          fromFieldPath: status.conditions[?(@.type=='Ready')].status
          toFieldPath: status.phase
          transforms:
            - type: map
              map:
                "True": Ready
                "False": Provisioning
                "Unknown": Provisioning

        # Compose a cluster FQDN from clusterPrefix + domain
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.clusterPrefix
              - fromFieldPath: spec.domain
            strategy: string
            string:
              fmt: "%s.%s"
          toFieldPath: status.clusterFqdn

        # expose where to find kubeconfig (secret name) in the composite status
        - type: FromCompositeFieldPath
          fromFieldPath: spec.customer
          toFieldPath: status.kubeconfigSecretName
          transforms:
            - type: string
              string:
                fmt: "enclave-%s-kubeconfig"

      connectionDetails:
        # Expose the kubeconfig secret name as a connection detail
        - name: kubeconfigSecretName
          fromFieldPath: status.kubeconfigSecretName
          fromConnectionSecretKey: kubeconfigSecretName
        # Expose the cluster FQDN as a connection detail
        - name: clusterFqdn
          fromFieldPath: status.clusterFqdn
          fromConnectionSecretKey: clusterFqdn