# -----------------------------------------------------------------------------
# EnclaveInstance - Composite Resource Definition (XRD)
# Defines the API for creating customer enclaves (Helm-based flow)
# -----------------------------------------------------------------------------
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: enclaveinstances.usenabla.com
spec:
  group: usenabla.com
  names:
    kind: EnclaveInstance
    plural: enclaveinstances
    shortNames:
      - enclave
      - enc
  claimNames:
    kind: EnclaveClaim
    plural: enclaveclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - customer
                - domain
                - azure
                - teleport
              properties:
                customer:
                  type: string
                  description: "Customer identifier (lowercase, alphanumeric)"
                  pattern: "^[a-z][a-z0-9-]*$"
                domain:
                  type: string
                  description: "Customer's domain for the enclave"
                clusterPrefix:
                  type: string
                  description: "Prefix for Teleport cluster FQDN"
                  default: "enclave"
                environment:
                  type: string
                  description: "Environment type"
                  enum:
                    - dev
                    - staging
                    - production
                  default: "production"
                azure:
                  type: object
                  required:
                    - subscriptionId
                    - region
                  properties:
                    subscriptionId:
                      type: string
                      description: "Azure subscription ID for this customer"
                    region:
                      type: string
                      description: "Azure region for deployment"
                      default: "eastus2"
                    resourceGroupName:
                      type: string
                      description: "Override resource group name (default: auto-generated)"
                teleport:
                  type: object
                  required:
                    - acmeEmail
                  properties:
                    acmeEmail:
                      type: string
                      description: "Email for Let's Encrypt certificates"
                    secondFactor:
                      type: string
                      enum:
                        - webauthn
                        - otp
                        - "off"
                      default: "webauthn"
                sizing:
                  type: string
                  description: "T-shirt size for the enclave"
                  enum:
                    - small
                    - medium
                    - large
                  default: "medium"
                features:
                  type: object
                  properties:
                    cuiEnabled:
                      type: boolean
                      description: "Enable CUI-isolated data tier (PostgreSQL + MinIO)"
                      default: true
                    observabilityEnabled:
                      type: boolean
                      description: "Enable Prometheus/Grafana stack"
                      default: true
                allowedRegistries:
                  type: array
                  description: "Container registries allowed for Application CRD"
                  items:
                    type: string
                  default:
                    - "cgr.dev/chainguard/*"
                    - "ghcr.io/*"
                    - "mcr.microsoft.com/*"
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Provisioning
                    - Ready
                    - Error
                    - Deleting
                clusterFqdn:
                  type: string
                  description: "Teleport cluster FQDN"
                kubeconfig:
                  type: string
                  description: "Inline kubeconfig (optional; may be omitted for secret-based reference)"
                kubeconfigSecretName:
                  type: string
                  description: "Name of the Secret (in crossplane-system) that contains the kubeconfig for the enclave's cluster"
                endpoints:
                  type: object
                  properties:
                    teleport:
                      type: string
                    grafana:
                      type: string
                    postgres:
                      type: string
                      description: "Standard PostgreSQL endpoint"
                    postgresCui:
                      type: string
                      description: "CUI PostgreSQL endpoint (if enabled)"
                    minio:
                      type: string
                      description: "Standard MinIO endpoint"
                    minioCui:
                      type: string
                      description: "CUI MinIO endpoint (if enabled)"
                message:
                  type: string
      additionalPrinterColumns:
        - name: Customer
          type: string
          jsonPath: .spec.customer
        - name: Domain
          type: string
          jsonPath: .spec.domain
        - name: Region
          type: string
          jsonPath: .spec.azure.region
        - name: CUI
          type: boolean
          jsonPath: .spec.features.cuiEnabled
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Teleport
          type: string
          jsonPath: .status.clusterFqdn
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      connectionDetails:
        # Expose the kubeconfig secret name so that consumers can easily find it
        - name: kubeconfigSecretName
          fromFieldPath: status.kubeconfigSecretName
        # Expose the cluster FQDN so that consumers can easily find it
        - name: clusterFqdn
          fromFieldPath: status.clusterFqdn