# -----------------------------------------------------------------------------
# EnclaveInstance Composition
# Maps EnclaveInstance spec to Terraform workspace
# Uses provider-terraform to run your existing Terraform modules
# -----------------------------------------------------------------------------
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: enclave-terraform
  labels:
    crossplane.io/xrd: enclaveinstances.usenabla.com
    provider: terraform
spec:
  compositeTypeRef:
    apiVersion: usenabla.com/v1alpha1
    kind: EnclaveInstance

  patchSets:
    - name: common-labels
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.customer
          toFieldPath: metadata.labels["usenabla.com/customer"]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.environment
          toFieldPath: metadata.labels["usenabla.com/environment"]

  resources:
    # -------------------------------------------------------------------------
    # Terraform Workspace - Provisions the entire enclave
    # -------------------------------------------------------------------------
    - name: terraform-workspace
      base:
        apiVersion: tf.upbound.io/v1beta1
        kind: Workspace
        spec:
          providerConfigRef:
            name: terraform-cloud
          forProvider:
            # Source from your Terraform repo
            source: Remote
            module: git::https://github.com/usenabla/nabla-enclave.git//enclave?ref=main
            # Variables passed to Terraform
            vars: []
            varFiles: []
          writeConnectionSecretToRef:
            namespace: crossplane-system
      patches:
        # Workspace name based on customer
        - type: FromCompositeFieldPath
          fromFieldPath: spec.customer
          toFieldPath: metadata.name
          transforms:
            - type: string
              string:
                fmt: "enclave-%s"

        # Connection secret name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.customer
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "enclave-%s-kubeconfig"

        # --- Terraform Variables ---

        # Environment
        - type: FromCompositeFieldPath
          fromFieldPath: spec.environment
          toFieldPath: spec.forProvider.vars[0]
          transforms:
            - type: string
              string:
                fmt: '{"key": "environment", "value": "%s"}'

        # Domain
        - type: FromCompositeFieldPath
          fromFieldPath: spec.domain
          toFieldPath: spec.forProvider.vars[1]
          transforms:
            - type: string
              string:
                fmt: '{"key": "domain", "value": "%s"}'

        # Cluster prefix
        - type: FromCompositeFieldPath
          fromFieldPath: spec.clusterPrefix
          toFieldPath: spec.forProvider.vars[2]
          transforms:
            - type: string
              string:
                fmt: '{"key": "cluster_prefix", "value": "%s"}'

        # Resource prefix (derived from customer name)
        - type: FromCompositeFieldPath
          fromFieldPath: spec.customer
          toFieldPath: spec.forProvider.vars[3]
          transforms:
            - type: string
              string:
                fmt: '{"key": "resource_prefix", "value": "%s"}'

        # Azure region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.azure.region
          toFieldPath: spec.forProvider.vars[4]
          transforms:
            - type: string
              string:
                fmt: '{"key": "location", "value": "%s"}'

        # Teleport ACME email
        - type: FromCompositeFieldPath
          fromFieldPath: spec.teleport.acmeEmail
          toFieldPath: spec.forProvider.vars[5]
          transforms:
            - type: string
              string:
                fmt: '{"key": "teleport_config", "value": "{\"acme_enabled\": true, \"acme_email\": \"%s\", \"second_factor\": \"webauthn\"}"}'

        # CUI enabled flag
        - type: FromCompositeFieldPath
          fromFieldPath: spec.features.cuiEnabled
          toFieldPath: spec.forProvider.vars[6]
          transforms:
            - type: string
              string:
                fmt: '{"key": "cui_enabled", "value": "%t"}'

        # --- Status Updates ---

        # Update status phase from Terraform state
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.state
          toFieldPath: status.phase
          transforms:
            - type: map
              map:
                Running: Provisioning
                Completed: Ready
                Failed: Error

        # Cluster FQDN to status
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.clusterPrefix
              - fromFieldPath: spec.domain
            strategy: string
            string:
              fmt: "%s.%s"
          toFieldPath: status.clusterFqdn

      connectionDetails:
        - name: kubeconfig
          fromConnectionSecretKey: kubeconfig
