# =============================================================================
# Nooklanes Namespaces - Swimlane Provisioning
# Creates isolated namespaces for CUI and Non-CUI workloads
# =============================================================================

---
# Non-CUI Workload Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.swimlanes.nonCui.workloadNamespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: nooklanes
    app.kubernetes.io/component: workload
    nooklanes.io/swimlane: "non-cui"
    nooklanes.io/data-classification: {{ .Values.swimlanes.nonCui.dataClassification }}
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityStandards.enforce }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurityStandards.audit }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurityStandards.warn }}

---
{{- if .Values.swimlanes.cuiEnabled }}
# CUI Workload Namespace (Isolated)
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.swimlanes.cui.workloadNamespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: nooklanes
    app.kubernetes.io/component: workload-cui
    nooklanes.io/swimlane: "cui"
    nooklanes.io/data-classification: {{ .Values.swimlanes.cui.dataClassification }}
    nooklanes.io/cui-authorized: "true"
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityStandards.enforce }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurityStandards.audit }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurityStandards.warn }}
{{- end }}

---
# Non-CUI PostgreSQL Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.swimlanes.nonCui.postgresNamespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: nooklanes
    app.kubernetes.io/component: database
    nooklanes.io/swimlane: "non-cui"
    nooklanes.io/data-classification: {{ .Values.swimlanes.nonCui.dataClassification }}
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityStandards.enforce }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurityStandards.audit }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurityStandards.warn }}

---
{{- if .Values.swimlanes.cuiEnabled }}
# CUI PostgreSQL Namespace (Isolated)
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.swimlanes.cui.postgresNamespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: nooklanes
    app.kubernetes.io/component: database-cui
    nooklanes.io/swimlane: "cui"
    nooklanes.io/data-classification: {{ .Values.swimlanes.cui.dataClassification }}
    nooklanes.io/cui-authorized: "true"
    nooklanes.io/encryption-required: "true"
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityStandards.enforce }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurityStandards.audit }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurityStandards.warn }}
{{- end }}

---
# Non-CUI MinIO Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.swimlanes.nonCui.minioNamespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: nooklanes
    app.kubernetes.io/component: object-storage
    nooklanes.io/swimlane: "non-cui"
    nooklanes.io/data-classification: {{ .Values.swimlanes.nonCui.dataClassification }}
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityStandards.enforce }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurityStandards.audit }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurityStandards.warn }}

---
{{- if .Values.swimlanes.cuiEnabled }}
# CUI MinIO Namespace (Isolated)
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.swimlanes.cui.minioNamespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: nooklanes
    app.kubernetes.io/component: object-storage-cui
    nooklanes.io/swimlane: "cui"
    nooklanes.io/data-classification: {{ .Values.swimlanes.cui.dataClassification }}
    nooklanes.io/cui-authorized: "true"
    nooklanes.io/encryption-required: "true"
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityStandards.enforce }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurityStandards.audit }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurityStandards.warn }}
{{- end }}
