# =============================================================================
# Nooklanes Network Policies - CUI Isolation
# Enforces strict network isolation between CUI and Non-CUI swimlanes
# CMMC AC.L2-3.1.3 - Control CUI flow
# =============================================================================

{{- if .Values.networkPolicies.enabled }}

---
# Default Deny All Traffic (Zero Trust)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Values.swimlanes.nonCui.workloadNamespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

---
{{- if .Values.swimlanes.cuiEnabled }}
# CUI Default Deny All Traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Values.swimlanes.cui.workloadNamespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
{{- end }}

---
{{- if .Values.networkPolicies.allowDNS }}
# Allow DNS queries from Non-CUI workloads
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: {{ .Values.swimlanes.nonCui.workloadNamespace }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
{{- end }}

---
{{- if and .Values.swimlanes.cuiEnabled .Values.networkPolicies.allowDNS }}
# Allow DNS queries from CUI workloads
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns
  namespace: {{ .Values.swimlanes.cui.workloadNamespace }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
{{- end }}

---
# Allow Non-CUI Workloads to access Non-CUI PostgreSQL
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-postgres-access
  namespace: {{ .Values.swimlanes.nonCui.postgresNamespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              nooklanes.io/swimlane: "non-cui"
      ports:
        - protocol: TCP
          port: 5432

---
# Allow Non-CUI Workloads to access Non-CUI MinIO
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-minio-access
  namespace: {{ .Values.swimlanes.nonCui.minioNamespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              nooklanes.io/swimlane: "non-cui"
      ports:
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 9001

---
{{- if .Values.swimlanes.cuiEnabled }}
# CUI Isolation: Only CUI workloads can access CUI PostgreSQL
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cui-postgres-isolation
  namespace: {{ .Values.swimlanes.cui.postgresNamespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # ONLY allow traffic from CUI workload namespace
    - from:
        - namespaceSelector:
            matchLabels:
              nooklanes.io/swimlane: "cui"
              nooklanes.io/cui-authorized: "true"
      ports:
        - protocol: TCP
          port: 5432
  egress:
    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
    # Allow access to CUI MinIO for backups
    - to:
        - namespaceSelector:
            matchLabels:
              nooklanes.io/data-classification: "cui"
      ports:
        - protocol: TCP
          port: 9000
{{- end }}

---
{{- if .Values.swimlanes.cuiEnabled }}
# CUI Isolation: Only CUI workloads can access CUI MinIO
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cui-minio-isolation
  namespace: {{ .Values.swimlanes.cui.minioNamespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # ONLY allow traffic from CUI swimlane
    - from:
        - namespaceSelector:
            matchLabels:
              nooklanes.io/swimlane: "cui"
              nooklanes.io/cui-authorized: "true"
      ports:
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 9001
  egress:
    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
{{- end }}

---
{{- if .Values.networkPolicies.cuiIsolation.enabled }}
# Explicit Block: Non-CUI workloads cannot access CUI data tier
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-non-cui-to-cui
  namespace: {{ .Values.swimlanes.nonCui.workloadNamespace }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # Allow all egress EXCEPT to CUI namespaces
    - to:
        - namespaceSelector:
            matchExpressions:
              - key: nooklanes.io/cui-authorized
                operator: DoesNotExist
{{- end }}

---
{{- if and .Values.swimlanes.cuiEnabled .Values.networkPolicies.cuiIsolation.enabled }}
# Explicit Block: CUI workloads cannot access Non-CUI data tier
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-cui-to-non-cui-data
  namespace: {{ .Values.swimlanes.cui.workloadNamespace }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
    # Allow access ONLY to CUI data tier
    - to:
        - namespaceSelector:
            matchLabels:
              nooklanes.io/cui-authorized: "true"
{{- end }}

---
{{- if .Values.networkPolicies.cuiIsolation.allowedCrossLaneTraffic }}
# Allow Observability to scrape metrics from both swimlanes
{{- range .Values.networkPolicies.cuiIsolation.allowedCrossLaneTraffic }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ .from }}-metrics
  namespace: {{ $.Values.swimlanes.nonCui.workloadNamespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .from }}
      ports:
        {{- range .ports }}
        - protocol: TCP
          port: {{ . }}
        {{- end }}
---
{{- if $.Values.swimlanes.cuiEnabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ .from }}-metrics
  namespace: {{ $.Values.swimlanes.cui.workloadNamespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .from }}
      ports:
        {{- range .ports }}
        - protocol: TCP
          port: {{ . }}
        {{- end }}
---
{{- end }}
{{- end }}
{{- end }}

{{- end }}
