{{- if .Values.observability.gatus.enabled }}
# =============================================================================
# Gatus - Health Monitoring and Status Page
# =============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
  namespace: observability
data:
  config.yaml: |
    metrics: true
    storage:
      type: memory
    endpoints:
      - name: Teleport
        url: "https://{{ .Values.global.domain }}/readyz"
        interval: 30s
        conditions:
          - "[STATUS] == 200"

      - name: OpenBao
        url: "http://openbao.openbao.svc.cluster.local:8200/v1/sys/health"
        interval: 30s
        conditions:
          - "[STATUS] == 200"

      - name: PostgreSQL (Non-CUI)
        url: "tcp://postgres-rw.{{ .Values.swimlanes.nonCui.postgresNamespace }}.svc.cluster.local:5432"
        interval: 30s
        conditions:
          - "[CONNECTED] == true"

      {{- if .Values.swimlanes.cuiEnabled }}
      - name: PostgreSQL (CUI)
        url: "tcp://postgres-cui-rw.{{ .Values.swimlanes.cui.postgresNamespace }}.svc.cluster.local:5432"
        interval: 30s
        conditions:
          - "[CONNECTED] == true"
      {{- end }}

      - name: MinIO (Non-CUI)
        url: "http://minio.{{ .Values.swimlanes.nonCui.minioNamespace }}.svc.cluster.local:9000/minio/health/live"
        interval: 30s
        conditions:
          - "[STATUS] == 200"

      {{- if .Values.swimlanes.cuiEnabled }}
      - name: MinIO (CUI)
        url: "http://minio-cui.{{ .Values.swimlanes.cui.minioNamespace }}.svc.cluster.local:9000/minio/health/live"
        interval: 30s
        conditions:
          - "[STATUS] == 200"
      {{- end }}

      - name: OPAL Server
        url: "http://opal-server.policy-system.svc.cluster.local:7002/healthcheck"
        interval: 30s
        conditions:
          - "[STATUS] == 200"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatus
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatus
  template:
    metadata:
      labels:
        app: gatus
    spec:
      containers:
        - name: gatus
          image: twinproduction/gatus:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            {{- toYaml .Values.observability.gatus.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: gatus-config

---
apiVersion: v1
kind: Service
metadata:
  name: gatus
  namespace: observability
spec:
  selector:
    app: gatus
  ports:
    - port: 8080
      targetPort: 8080
{{- end }}
