{{- if .Values.secrets.enabled }}
# =============================================================================
# OpenBao StatefulSet - Secrets Management with Raft HA
# Supports multiple auto-unseal backends
# =============================================================================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openbao
  namespace: openbao
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: openbao-internal
  replicas: {{ .Values.secrets.openbao.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: openbao
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openbao
        app.kubernetes.io/component: secrets
    spec:
      serviceAccountName: openbao
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        fsGroup: 1000
      containers:
        - name: openbao
          image: quay.io/openbao/openbao:2.0.0
          imagePullPolicy: IfNotPresent
          command: ["bao", "server", "-config=/openbao/config/openbao.hcl"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- if eq .Values.secrets.openbao.seal.type "azurekeyvault" }}
            - name: AZURE_TENANT_ID
              value: "{{ .Values.secrets.openbao.seal.azurekeyvault.tenantId }}"
            {{- end }}
            {{- if eq .Values.secrets.openbao.seal.type "transit" }}
            - name: TRANSIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: openbao-transit-token
                  key: token
            {{- end }}
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
            - name: internal
              containerPort: 8201
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /openbao/data
            - name: config
              mountPath: /openbao/config
            {{- if .Values.secrets.openbao.audit.enabled }}
            - name: audit
              mountPath: /openbao/audit
            {{- end }}
          resources:
            {{- toYaml .Values.secrets.openbao.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          configMap:
            name: openbao-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if or .Values.secrets.openbao.storage.storageClass .Values.global.storageClass }}
        storageClassName: {{ .Values.secrets.openbao.storage.storageClass | default .Values.global.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.secrets.openbao.storage.size }}
    {{- if .Values.secrets.openbao.audit.enabled }}
    - metadata:
        name: audit
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if or .Values.secrets.openbao.storage.storageClass .Values.global.storageClass }}
        storageClassName: {{ .Values.secrets.openbao.storage.storageClass | default .Values.global.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: 10Gi
    {{- end }}
---
# Service Account for OpenBao
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao
  namespace: openbao
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/component: secrets
  {{- if eq .Values.secrets.openbao.seal.type "azurekeyvault" }}
  annotations:
    azure.workload.identity/client-id: "{{ .Values.secrets.openbao.seal.azurekeyvault.clientId }}"
  {{- end }}
---
# Headless service for Raft cluster
apiVersion: v1
kind: Service
metadata:
  name: openbao-internal
  namespace: openbao
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/component: secrets
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: internal
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/name: openbao
---
# Public service for API access
apiVersion: v1
kind: Service
metadata:
  name: openbao
  namespace: openbao
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/component: secrets
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8200
      targetPort: 8200
  selector:
    app.kubernetes.io/name: openbao
{{- end }}
