{{- if and .Values.secrets.openbaoCui.enabled .Values.swimlanes.cuiEnabled }}
# =============================================================================
# OpenBao-CUI StatefulSet - Secrets Management for CUI Workloads
# CMMC AC.L2-3.1.3 - Separate cryptographic boundary for CUI
# =============================================================================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openbao-cui
  namespace: openbao-cui
  labels:
    app.kubernetes.io/name: openbao-cui
    app.kubernetes.io/component: secrets-cui
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    nooklanes.io/cui-authorized: "true"
spec:
  serviceName: openbao-cui-internal
  replicas: {{ .Values.secrets.openbaoCui.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: openbao-cui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openbao-cui
        app.kubernetes.io/component: secrets-cui
        nooklanes.io/cui-authorized: "true"
      annotations:
        # Force pod restart on config changes
        checksum/config: {{ include (print $.Template.BasePath "/secrets/openbao-cui-config.yaml") . | sha256sum }}
    spec:
      serviceAccountName: openbao-cui
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        fsGroup: 1000
        # CUI-specific: Enhanced security context
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: openbao
          image: quay.io/openbao/openbao:2.0.0
          imagePullPolicy: IfNotPresent
          command: ["bao", "server", "-config=/openbao/config/openbao.hcl"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SKIP_SETCAP
              value: "true"
            {{- if eq .Values.secrets.openbaoCui.seal.type "awskms" }}
            - name: AWS_REGION
              value: {{ .Values.secrets.openbaoCui.seal.awskms.region | quote }}
            {{- end }}
            {{- if eq .Values.secrets.openbaoCui.seal.type "azurekeyvault" }}
            - name: AZURE_TENANT_ID
              value: {{ .Values.secrets.openbaoCui.seal.azurekeyvault.tenantId | quote }}
            {{- end }}
            {{- if eq .Values.secrets.openbaoCui.seal.type "transit" }}
            - name: TRANSIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: openbao-cui-transit-token
                  key: token
            {{- end }}
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
            - name: internal
              containerPort: 8201
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /v1/sys/health?standbyok=true
              port: 8200
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /openbao/data
            - name: config
              mountPath: /openbao/config
            - name: audit
              mountPath: /openbao/audit
          resources:
            {{- toYaml .Values.secrets.openbaoCui.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: config
          configMap:
            name: openbao-cui-config
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          nooklanes.io/cui-authorized: "true"
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if or .Values.secrets.openbaoCui.storage.storageClass .Values.global.storageClass }}
        storageClassName: {{ .Values.secrets.openbaoCui.storage.storageClass | default .Values.global.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.secrets.openbaoCui.storage.size }}
    - metadata:
        name: audit
        labels:
          nooklanes.io/cui-authorized: "true"
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if or .Values.secrets.openbaoCui.storage.storageClass .Values.global.storageClass }}
        storageClassName: {{ .Values.secrets.openbaoCui.storage.storageClass | default .Values.global.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: 10Gi

---
# Service Account for OpenBao-CUI
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openbao-cui
  namespace: openbao-cui
  labels:
    app.kubernetes.io/name: openbao-cui
    app.kubernetes.io/component: secrets-cui
    nooklanes.io/cui-authorized: "true"
  {{- if eq .Values.secrets.openbaoCui.seal.type "awskms" }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.secrets.openbaoCui.seal.awskms.roleArn | quote }}
  {{- else if eq .Values.secrets.openbaoCui.seal.type "azurekeyvault" }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.secrets.openbaoCui.seal.azurekeyvault.clientId | quote }}
  {{- end }}

---
# Headless service for Raft cluster
apiVersion: v1
kind: Service
metadata:
  name: openbao-cui-internal
  namespace: openbao-cui
  labels:
    app.kubernetes.io/name: openbao-cui
    app.kubernetes.io/component: secrets-cui
    nooklanes.io/cui-authorized: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: internal
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/name: openbao-cui

---
# Public service for API access (CUI workloads only)
apiVersion: v1
kind: Service
metadata:
  name: openbao-cui
  namespace: openbao-cui
  labels:
    app.kubernetes.io/name: openbao-cui
    app.kubernetes.io/component: secrets-cui
    nooklanes.io/cui-authorized: "true"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8200
      targetPort: 8200
  selector:
    app.kubernetes.io/name: openbao-cui
{{- end }}
