{{- if and .Values.secrets.openbaoCui.enabled .Values.swimlanes.cuiEnabled .Values.networkPolicies.enabled }}
# =============================================================================
# OpenBao-CUI Network Policy
# CMMC AC.L2-3.1.3 - Enforce CUI secrets isolation
# ONLY CUI workloads can access OpenBao-CUI
# =============================================================================
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: openbao-cui-isolation
  namespace: openbao-cui
  labels:
    app.kubernetes.io/name: openbao-cui
    app.kubernetes.io/component: secrets-cui
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openbao-cui
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # ONLY allow traffic from CUI-authorized namespaces
    - from:
        - namespaceSelector:
            matchLabels:
              nooklanes.io/cui-authorized: "true"
      ports:
        - protocol: TCP
          port: 8200
        - protocol: TCP
          port: 8201
    # Allow internal Raft cluster communication
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: openbao-cui
      ports:
        - protocol: TCP
          port: 8200
        - protocol: TCP
          port: 8201
  egress:
    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
    # Allow internal cluster communication
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: openbao-cui
      ports:
        - protocol: TCP
          port: 8200
        - protocol: TCP
          port: 8201
    {{- if eq .Values.secrets.openbaoCui.seal.type "awskms" }}
    # Allow access to AWS KMS for auto-unseal
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
    {{- else if eq .Values.secrets.openbaoCui.seal.type "azurekeyvault" }}
    # Allow access to Azure Key Vault for auto-unseal
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
    {{- else if eq .Values.secrets.openbaoCui.seal.type "gcpckms" }}
    # Allow access to GCP KMS for auto-unseal
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
    {{- end }}

---
# Explicitly block non-CUI workloads from accessing OpenBao-CUI
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-non-cui-to-openbao-cui
  namespace: {{ .Values.swimlanes.nonCui.workloadNamespace }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # Allow all egress EXCEPT to openbao-cui namespace
    - to:
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: NotIn
                values:
                  - openbao-cui
{{- end }}
