# -----------------------------------------------------------------------------
# Crossplane Terraform Provider
# Uses your existing Terraform modules to provision enclaves
# This is the bridge between Crossplane and your Terraform codebase
# -----------------------------------------------------------------------------
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-terraform
spec:
  package: xpkg.upbound.io/upbound/provider-terraform:v0.18.0
  controllerConfigRef:
    name: provider-terraform-config
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: provider-terraform-config
spec:
  args:
    - --debug
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 256Mi
---
# Provider configuration - connects to Terraform Cloud
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: terraform-cloud
spec:
  # Use Terraform Cloud as backend
  configuration: |
    terraform {
      cloud {
        organization = "usenabla"
        workspaces {
          tags = ["enclave"]
        }
      }
    }

    provider "azurerm" {
      features {}
    }
  credentials:
    - filename: terraform.tfvars
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: terraform-cloud-creds
        key: credentials
