# -----------------------------------------------------------------------------
# Example: Customer Enclave Claim
# This is what you'd create to provision a new customer
# -----------------------------------------------------------------------------
apiVersion: usenabla.com/v1alpha1
kind: EnclaveClaim
metadata:
  name: acme-corp
  namespace: customers  # Namespace for customer claims
spec:
  # Customer identification
  customer: acme-corp
  domain: acme-corp.com
  clusterPrefix: enclave
  environment: production

  # Azure configuration
  azure:
    subscriptionId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"  # Customer's Azure sub
    region: eastus2

  # Teleport configuration
  teleport:
    acmeEmail: admin@acme-corp.com
    secondFactor: webauthn

  # Sizing (maps to node pool configurations)
  sizing: medium

  # Feature flags
  features:
    cuiEnabled: true           # CUI-isolated PostgreSQL + MinIO
    observabilityEnabled: true # Prometheus/Grafana stack

---
# -----------------------------------------------------------------------------
# Example: Small Dev/Test Customer (No CUI)
# -----------------------------------------------------------------------------
apiVersion: usenabla.com/v1alpha1
kind: EnclaveClaim
metadata:
  name: startup-xyz
  namespace: customers
spec:
  customer: startup-xyz
  domain: startup-xyz.io
  clusterPrefix: secure
  environment: dev

  azure:
    subscriptionId: "yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy"
    region: westus2

  teleport:
    acmeEmail: devops@startup-xyz.io
    secondFactor: otp  # OTP for smaller team

  sizing: small

  features:
    cuiEnabled: false          # No CUI needed for dev
    observabilityEnabled: true

---
# -----------------------------------------------------------------------------
# Example: Large Enterprise Customer (Defense)
# -----------------------------------------------------------------------------
apiVersion: usenabla.com/v1alpha1
kind: EnclaveClaim
metadata:
  name: bigcorp-defense
  namespace: customers
spec:
  customer: bigcorp-defense
  domain: bigcorp.mil
  clusterPrefix: enclave
  environment: production

  azure:
    subscriptionId: "zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz"
    region: usgovvirginia  # Azure Government

  teleport:
    acmeEmail: security@bigcorp.mil
    secondFactor: webauthn

  sizing: large

  features:
    cuiEnabled: true           # CUI required for defense
    observabilityEnabled: true

  # Custom allowed registries for this customer
  allowedRegistries:
    - "cgr.dev/chainguard/*"
    - "ghcr.io/bigcorp-defense/*"
    - "mcr.microsoft.com/*"
